kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: python:3.8-alpine
    pull: if-not-exists
    commands:
      - chmod +x prnt.sc_link_generator.py
      - ./prnt.sc_link_generator.py